// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const navLinks: string;
export const navLinkItem: string;
export const navLinkText: string;
